# Generated by Django 5.2.9 on 2025-12-18 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_customuser_name'),
        ('backend', '0004_alter_caste_level_alter_caste_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MatrimonyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('this_account_for', models.CharField(choices=[('son', 'Son'), ('daughter', 'Daughter'), ('brother', 'Brother'), ('sister', 'Sister'), ('friend', 'Friend')], max_length=20)),
                ('mother_tongue', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('looking_for', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('height', models.CharField(max_length=10)),
                ('physical_status', models.CharField(choices=[('normal', 'Normal'), ('challenged', 'Physically Challenged')], max_length=20)),
                ('marital_status', models.CharField(choices=[('never_married', 'Never Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Separated')], max_length=20)),
                ('children_count', models.PositiveIntegerField(blank=True, null=True)),
                ('children_with_me', models.BooleanField(blank=True, null=True)),
                ('sub_caste', models.CharField(blank=True, max_length=100, null=True)),
                ('willing_inter_caste', models.BooleanField(default=False)),
                ('education', models.CharField(choices=[('diploma', 'Diploma'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD'), ('professional', 'Professional Degree'), ('other', 'Other')], max_length=20)),
                ('field_of_study', models.CharField(max_length=100)),
                ('occupation', models.CharField(choices=[('software', 'Software Engineer'), ('doctor', 'Doctor'), ('teacher', 'Teacher'), ('business', 'Business'), ('govt', 'Govt Service'), ('banking', 'Banking'), ('other', 'Other')], max_length=20)),
                ('annual_income', models.CharField(choices=[('2-5', '2–5 Lakhs'), ('5-10', '5–10 Lakhs'), ('10-15', '10–15 Lakhs'), ('15-25', '15–25 Lakhs'), ('25-50', '25–50 Lakhs'), ('50+', '50+ Lakhs')], max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('family_status', models.CharField(choices=[('middle', 'Middle Class'), ('upper_middle', 'Upper Middle Class'), ('rich', 'Rich')], max_length=20)),
                ('family_worth', models.CharField(choices=[('5', '5 Lakh'), ('5-10', '5–10 Lakh'), ('10-25', '10–25 Lakh'), ('25-50', '25–50 Lakh'), ('50-100', '50 Lakh – 1 Crore'), ('1cr+', '1 Crore+')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caste', models.ForeignKey(limit_choices_to={'level': 'caste'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caste_profiles', to='backend.caste')),
                ('religion', models.ForeignKey(limit_choices_to={'level': 'religion'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='religion_profiles', to='backend.caste')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
