# Generated by Django 5.2.9 on 2025-12-18 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_customuser_is_email_verified_matrimonyprofile'),
        ('backend', '0005_moviegenre_musicactivity_musicgenre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalLifestyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_language', models.CharField(blank=True, max_length=100)),
                ('favorite_sports', models.CharField(blank=True, max_length=100)),
                ('fitness_activity', models.CharField(blank=True, max_length=100)),
                ('spoken_languages', models.CharField(blank=True, max_length=200)),
                ('cooking', models.BooleanField(default=False)),
                ('time_of_birth', models.TimeField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=100)),
                ('nakshatra', models.CharField(blank=True, max_length=50)),
                ('rashi', models.CharField(blank=True, max_length=50)),
                ('eating_habits', models.CharField(choices=[('eggetarian', 'Eggetarian'), ('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian')], max_length=20)),
                ('smoking', models.CharField(choices=[('never', 'Never'), ('occasionally', 'Occasionally'), ('regularly', 'Regularly'), ('quit', 'Quit')], max_length=20)),
                ('drinking', models.CharField(choices=[('never', 'Never'), ('occasionally', 'Occasionally'), ('regularly', 'Regularly'), ('quit', 'Quit')], max_length=20)),
                ('college', models.CharField(blank=True, max_length=150)),
                ('course_degree', models.CharField(blank=True, max_length=100)),
                ('passing_year', models.PositiveIntegerField(blank=True, null=True)),
                ('movie_tv_genres', models.ManyToManyField(blank=True, to='backend.moviegenre')),
                ('music_activities', models.ManyToManyField(blank=True, to='backend.musicactivity')),
                ('music_genres', models.ManyToManyField(blank=True, to='backend.musicgenre')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifestyle', to='auth_api.matrimonyprofile')),
                ('reading_preferences', models.ManyToManyField(blank=True, to='backend.readingpreference')),
            ],
        ),
    ]
