# Generated by Django 5.2.9 on 2025-12-23 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0007_userimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrimonyprofile',
            name='looking_for',
        ),
    ]
