# Generated by Django 5.2.9 on 2025-12-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0009_subscriptionpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='payment_method',
            field=models.CharField(default='razorpay', max_length=20),
        ),
    ]
