# Generated by Django 5.2.9 on 2025-12-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0010_alter_subscriptionpayment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='this_account_for',
            field=models.CharField(choices=[('son', 'Son'), ('daughter', 'Daughter'), ('brother', 'Brother'), ('sister', 'Sister'), ('friend', 'Friend'), ('myself', 'Myself'), ('relative', 'Relative')], max_length=20),
        ),
    ]
