# Generated by Django 5.2.9 on 2025-12-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0011_alter_matrimonyprofile_this_account_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('sub_admin', 'Sub Admin')], default='user', max_length=20),
        ),
    ]
