# Generated by Django 5.2.9 on 2026-02-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0017_phoneotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
