# Generated by Django 5.2.9 on 2026-02-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0020_customuser_deleted_at_customuser_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrimonyprofile',
            name='job_type',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('government', 'Government'), ('business', 'Business')], max_length=20, null=True),
        ),
    ]
