# Generated by Django 5.2.9 on 2025-12-17 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('caste_type', models.CharField(choices=[('caste', 'Caste'), ('sub_caste', 'Sub Caste')], max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_castes', to='backend.caste')),
            ],
            options={
                'verbose_name': 'Caste',
                'verbose_name_plural': 'Castes',
                'unique_together': {('name', 'parent')},
            },
        ),
    ]
