# Generated by Django 5.2.9 on 2025-12-17 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Caste',
        ),
    ]
