# Generated by Django 5.2.9 on 2025-12-17 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0002_delete_caste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('religion', 'Religion'), ('caste', 'Caste'), ('sub_caste', 'Sub Caste')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='backend.caste')),
            ],
            options={
                'verbose_name': 'Religion / Caste',
                'verbose_name_plural': 'Religions & Castes',
                'unique_together': {('name', 'parent')},
            },
        ),
    ]
