# Generated by Django 5.2.9 on 2025-12-18 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caste',
            name='level',
            field=models.CharField(choices=[('religion', 'Religion'), ('caste', 'Caste')], max_length=20),
        ),
        migrations.AlterField(
            model_name='caste',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='castes', to='backend.caste'),
        ),
    ]
