# Generated by Django 5.2.9 on 2025-12-29 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_sidebarmenu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAdminMenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.sidebarmenu')),
                ('sub_admin', models.ForeignKey(limit_choices_to={'role': 'sub_admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='menu_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sub_admin', 'menu')},
            },
        ),
    ]
