# Generated by Django 5.2.9 on 2026-01-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='blog',
            name='cover_media',
            field=models.FileField(blank=True, help_text='Upload cover image (JPG, PNG) or video (MP4, WebM)', null=True, upload_to='blogs/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='cover_media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video')], max_length=10, null=True),
        ),
    ]
