# Generated by Django 5.2.9 on 2026-02-04 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_reportreason_userreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportreason',
            name='description',
        ),
    ]
