# Generated by Django 5.2.9 on 2026-02-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_remove_reportreason_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='reveal_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
