# Generated by Django 5.2.9 on 2026-01-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predefinedanswer',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='predefinedmessage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='predefinedanswer',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of answers'),
        ),
        migrations.AddField(
            model_name='predefinedmessage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which questions should appear'),
        ),
    ]
