# Generated by Django 5.2.9 on 2026-01-20 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_predefinedanswer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predefinedanswer',
            name='message',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='PredefinedAnswer',
        ),
        migrations.DeleteModel(
            name='PredefinedMessage',
        ),
    ]
