# Generated by Django 5.2.9 on 2026-01-16 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_successstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='success_stories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('success_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='match.successstory')),
            ],
        ),
    ]
