# Generated by Django 5.2.9 on 2026-01-20 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_freecontactview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FreeContactView',
        ),
    ]
